/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 * Generated at 2023-09-12 12:05:39
 * Version: v2023.09.12_6da53bd7
 */

#include "Font_Lib.h"


const font_type_info_t Full_HarmonyOS_Sans_SC_Medium_24_2Bpp_font_info =
{
    .font_name       = "Full_HarmonyOS_Sans_SC_Medium_24_2Bpp",
    .bpp             = 2,
    .cmap_continued  = 1,
    .y_size          = 32,
    .y_dist          = 32,
    .baseline        = 27,
    .l_hight         = 0,
    .c_hight         = 0,
    .first_code      = 0x0,
    .last_code       = 0xffff,
    .cmap_offset     = 0x4dc4,
    .code_num        = 65535,
#if !CMAP_HASH_ENABLE
    .p_cmap_table    = NULL,
#else
    .p_cmap_table    = NULL,
#endif
};

