/*
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: 
 * Generated at 2022-12-07 13:50:30
 * Version: 0x91fcc446
 */

#include "Font_Lib.h"


const font_type_info_t fHarmonyOS_Sans_SC_Medium_24_2Bpp_font_info =
{
    .font_name       = "fHarmonyOS_Sans_SC_Medium_24_2Bpp",
    .bpp             = 2,
    .cmap_continued  = 1,
    .y_size          = 23,
    .y_dist          = 23,
    .baseline        = 18,
    .l_hight         = 0,
    .c_hight         = 0,
    .first_code      = 0x0,
    .last_code       = 0xffff,
    .cmap_offset     = 0x22fdd,
    .code_num        = 65535,
#if !CMAP_HASH_ENABLE
    .p_cmap_table    = NULL,
#else
    .p_cmap_table    = NULL,
#endif
};

