/*
 * This file is generated by py_FontMaker generation tools
 * you can porting your external storage
 *
 * author: John
 * github: 
 */
#include "ext_font_app.h"
#include "ext_font_engine.h"

/*Add the external storage driver header file*/

/*******************************************************************************************************
 *         Please include your header file and replace it with your print function
*******************************************************************************************************/
#include "bsp_qspi_dri.h"
#include <rtthread.h>

#define LOG_TAG     "font_app"
#define LOG_E       rt_kprintf
#define LOG_W       rt_kprintf
#define LOG_I       rt_kprintf
#define LOG_D       rt_kprintf
/*******************************************************************************************************/

/* Define your font 
 * eg: public_font_t HarmonyOS_24_2BPP
 */
public_font_t HarmonyOS_Sans_SC_Medium_24_2Bpp;
public_font_t fHarmonyOS_Sans_SC_Medium_24_2Bpp;


/* Define your font type table
 * eg: &HarmonyOS_24_2BPP
 */
const public_font_t *font_type_tbale[]={
    &HarmonyOS_Sans_SC_Medium_24_2Bpp,
    &fHarmonyOS_Sans_SC_Medium_24_2Bpp,
    &fake_font,
    &interior_font_HarmonyOS_Sans_SC_Medium_24_2bpp,
};


static uint32_t font_get_data(uint32_t offset, uint8_t *pbuf, uint32_t size)
{
/*******************************************************************************************************
 *             Please implement your read operation interface
 *******************************************************************************************************/
    #define EXT_FONT_FLASH_START_ADDR 0x00
    uint32_t read_size = 0;
    uint32_t err_code = bsp_qspi_flash_read(pbuf, size, EXT_FONT_FLASH_START_ADDR + offset);
    //if err_code == SUCCESS)
    {
        read_size = size;
    }
/*******************************************************************************************************/

    return read_size;
}

bool app_ext_font_init(void)
{
    uint32_t res = 0;
/* creat your font library
 * eg: res += ext_font_create(e_HarmonyOS_24_2BPP, &HarmonyOS_24_2BPP, &HarmonyOS_24_2BPP_font_info,font_get_data);
 */
    res += ext_font_create(e_HarmonyOS_Sans_SC_Medium_24_2Bpp, &HarmonyOS_Sans_SC_Medium_24_2Bpp, &HarmonyOS_Sans_SC_Medium_24_2Bpp_font_info, font_get_data);
    res += ext_font_create(e_fHarmonyOS_Sans_SC_Medium_24_2Bpp, &fHarmonyOS_Sans_SC_Medium_24_2Bpp, &fHarmonyOS_Sans_SC_Medium_24_2Bpp_font_info, font_get_data);
    if(res != 0)
    {
        return false;
    }

    return true;
}

FONTTYPE_ENUM app_font_get_type(const public_font_t *pFont)
{
    FONTTYPE_ENUM font_type;
    for (font_type = (FONTTYPE_ENUM)0; font_type < e_FontTypeMax; font_type ++)
    {
         if (pFont == font_type_tbale[font_type])
         {
              return font_type;
         }
    }
    return e_FontTypeMax;
}

public_font_t* app_type_get_font(FONTTYPE_ENUM font_type)
{
     if (font_type < e_FontTypeMax)
     {
          return (public_font_t*)font_type_tbale[font_type];
     }
     else
     {
         return NULL;
     }
}




