/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#ifndef _ICON_FONT_DEF_H_
#define _ICON_FONT_DEF_H_

#ifdef __cplusplus
extern "C" {
#endif


#define ICON_SYMBOL_CUT                               "\xEE\x98\x80"      /*58880,  0xE600*/
#define ICON_SYMBOL_CLOSE                             "\xEE\x98\x81"      /*58881,  0xE601*/
#define ICON_SYMBOL_NEXT                              "\xEE\x98\x82"      /*58882,  0xE602*/
#define ICON_SYMBOL_CALL_1                            "\xEE\x98\x9E"      /*58910,  0xE61E*/
#define ICON_SYMBOL_PASTE                             "\xEE\x98\xA1"      /*58913,  0xE621*/
#define ICON_SYMBOL_BATTERY_1                         "\xEE\x98\xA2"      /*58914,  0xE622*/
#define ICON_SYMBOL_BATTERY_CHARGE                    "\xEE\x98\xAA"      /*58922,  0xE62A*/
#define ICON_SYMBOL_WIFI                              "\xEE\x98\xB2"      /*58930,  0xE632*/
#define ICON_SYMBOL_BATTERY_0                         "\xEE\x98\xBD"      /*58941,  0xE63D*/
#define ICON_SYMBOL_BATTERY_3                         "\xEE\x98\xBF"      /*58943,  0xE63F*/
#define ICON_SYMBOL_LIST                              "\xEE\x99\x83"      /*58947,  0xE643*/
#define ICON_SYMBOL_OK                                "\xEE\x99\x91"      /*58961,  0xE651*/
#define ICON_SYMBOL_BLUETOOTH                         "\xEE\x99\x92"      /*58962,  0xE652*/
#define ICON_SYMBOL_PREVIOUS                          "\xEE\x99\x98"      /*58968,  0xE658*/
#define ICON_SYMBOL_SETTINGS                          "\xEE\x99\x9D"      /*58973,  0xE65D*/
#define ICON_SYMBOL_IC24_VOLUME_MAX                   "\xEE\x99\xA5"      /*58981,  0xE665*/
#define ICON_SYMBOL_GPS2                              "\xEE\x99\xAB"      /*58987,  0xE66B*/
#define ICON_SYMBOL_ICON_EYE_CLOSE2                   "\xEE\x99\xAC"      /*58988,  0xE66C*/
#define ICON_SYMBOL_POWER                             "\xEE\x99\xB1"      /*58993,  0xE671*/
#define ICON_SYMBOL_KEYBOARD                          "\xEE\x99\xB5"      /*58997,  0xE675*/
#define ICON_SYMBOL_PAUSE                             "\xEE\x99\xB6"      /*58998,  0xE676*/
#define ICON_SYMBOL_AUDIO                             "\xEE\x99\xB8"      /*59000,  0xE678*/
#define ICON_SYMBOL_SHUFFLE                           "\xEE\x99\xBE"      /*59006,  0xE67E*/
#define ICON_SYMBOL_COPY                              "\xEE\x99\xBF"      /*59007,  0xE67F*/
#define ICON_SYMBOL_EYE_OPEN                          "\xEE\x9A\x80"      /*59008,  0xE680*/
#define ICON_SYMBOL_STOP                              "\xEE\x9A\x86"      /*59014,  0xE686*/
#define ICON_SYMBOL_RIGHT                             "\xEE\x9A\xA3"      /*59043,  0xE6A3*/
#define ICON_SYMBOL_HARD_DRIVE                        "\xEE\x9A\xB9"      /*59065,  0xE6B9*/
#define ICON_SYMBOL_WARNING                           "\xEE\x9A\xBE"      /*59070,  0xE6BE*/
#define ICON_SYMBOL_MUTE                              "\xEE\x9C\x80"      /*59136,  0xE700*/
#define ICON_SYMBOL_USB                               "\xEE\x9C\xAD"      /*59181,  0xE72D*/
#define ICON_SYMBOL_PLAY_FILL                         "\xEE\x9D\x8F"      /*59215,  0xE74F*/
#define ICON_SYMBOL_VIDEO                             "\xEE\x9D\x98"      /*59224,  0xE758*/
#define ICON_SYMBOL_REFRESH                           "\xEE\x9E\x8F"      /*59279,  0xE78F*/
#define ICON_SYMBOL_SD                                "\xEE\x9F\x9D"      /*59357,  0xE7DD*/
#define ICON_SYMBOL_EDIT                              "\xEE\x9F\xA1"      /*59361,  0xE7E1*/
#define ICON_SYMBOL_LEFT                              "\xEE\x9F\xAB"      /*59371,  0xE7EB*/
#define ICON_SYMBOL_MINUS                             "\xEE\xA0\xA8"      /*59432,  0xE828*/
#define ICON_SYMBOL_SAVE                              "\xEE\xA0\xAC"      /*59436,  0xE82C*/
#define ICON_SYMBOL_UPLOAD                            "\xEE\xA0\xBB"      /*59451,  0xE83B*/
#define ICON_SYMBOL_ANGLE_DOWN                        "\xEE\xA1\x8C"      /*59468,  0xE84C*/
#define ICON_SYMBOL_ANGLE_UP                          "\xEE\xA1\x8D"      /*59469,  0xE84D*/
#define ICON_SYMBOL_FILE_FILL                         "\xEE\xA1\x97"      /*59479,  0xE857*/
#define ICON_SYMBOL_BACKSPACE                         "\xEE\xA1\x9C"      /*59484,  0xE85C*/
#define ICON_SYMBOL_IMAGE_FILL                        "\xEE\xA1\xA0"      /*59488,  0xE860*/
#define ICON_SYMBOL_HOME_FILL                         "\xEE\xA1\xA7"      /*59495,  0xE867*/
#define ICON_SYMBOL_BATTERY_4                         "\xEE\xA3\x8C"      /*59596,  0xE8CC*/
#define ICON_SYMBOL_BATTERY_2                         "\xEE\xA3\x8D"      /*59597,  0xE8CD*/
#define ICON_SYMBOL_BELL                              "\xEE\xA3\x8E"      /*59598,  0xE8CE*/
#define ICON_SYMBOL_DOWNLOAD                          "\xEE\xA3\xA4"      /*59620,  0xE8E4*/
#define ICON_SYMBOL_EJECT                             "\xEE\xA3\xA5"      /*59621,  0xE8E5*/
#define ICON_SYMBOL_PLUS                              "\xEE\xA3\xBE"      /*59646,  0xE8FE*/
#define ICON_SYMBOL_TRASH                             "\xEE\xA4\xA6"      /*59686,  0xE926*/
#define ICON_SYMBOL_24GF_FOLDEROPEN                   "\xEE\xAB\x85"      /*60101,  0xEAC5*/
#define ICON_SYMBOL_24GL_ENTER2                       "\xEE\xAD\xAC"      /*60268,  0xEB6C*/
#define ICON_SYMBOL_IC24_VOLUME_MID                   "\xEF\x8C\x94"      /*62228,  0xF314*/

#ifdef __cplusplus
}
#endif

#endif


