/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_zh_hk_translation = {
    .key_nextstep         = "下一步",
    .key_cancel           = "取消",
    .key_alarm            = "鬧鐘",
    .key_remind_later     = "稍後提醒",
    .key_delete           = "刪除",
    .key_everyday         = "每天",
    .key_setting          = "設定",
    .key_heart_rate       = "心率",
    .key_about            = "關於",
    .key_flashlight       = "手電筒",
    .key_music            = "音樂",
    .key_powerOff         = "關機",
};

const language_info_t lang_zh_hk = {
    .locale = "繁體中文",
    .translation = &lang_zh_hk_translation,
};


