/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_it_IT_translation = {
    .key_nextstep         = "Prossimo passo",
    .key_cancel           = "Annulla",
    .key_alarm            = "Sveglia",
    .key_remind_later     = "Avvisare più tardi",
    .key_delete           = "Eliminare",
    .key_everyday         = "Ogni giorno",
    .key_setting          = "Impostazioni",
    .key_heart_rate       = "Cardiofrequenza",
    .key_about            = "Su",
    .key_flashlight       = "Torcia",
    .key_music            = "Musica",
    .key_powerOff         = "Spegnimento",
};

const language_info_t lang_it_IT = {
    .locale = "Italiano",
    .translation = &lang_it_IT_translation,
};


