/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#ifndef __LANGUAGE_H__
#define __LANGUAGE_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LANGUAGE_EN_US,
    LANGUAGE_ZH_CN,
    LANGUAGE_ZH_HK,
    LANGUAGE_DE_DE,
    LANGUAGE_IT_IT,
    LANGUAGE_JA_JP,
    LANGUAGE_PT_PT,
    LANGUAGE_ES_ES,
    LANGUAGE_RU_RU,
    LANGUAGE_FR_FR,
    LANGUAGE_TYPE_MAX,
} LANGUAGE_TYPE;

typedef struct {
    const char *lang_string;
} LANG_TRANSLA_ITEM_t;

typedef struct {
    LANG_TRANSLA_ITEM_t key_nextstep;
    LANG_TRANSLA_ITEM_t key_cancel;
    LANG_TRANSLA_ITEM_t key_alarm;
    LANG_TRANSLA_ITEM_t key_remind_later;
    LANG_TRANSLA_ITEM_t key_delete;
    LANG_TRANSLA_ITEM_t key_everyday;
    LANG_TRANSLA_ITEM_t key_setting;
    LANG_TRANSLA_ITEM_t key_heart_rate;
    LANG_TRANSLA_ITEM_t key_about;
    LANG_TRANSLA_ITEM_t key_flashlight;
    LANG_TRANSLA_ITEM_t key_music;
    LANG_TRANSLA_ITEM_t key_powerOff;
} LANGUAGE_TRANSLATION_t;

typedef struct {
    const char *locale;
    const LANGUAGE_TRANSLATION_t *translation;
} language_info_t;


extern void app_set_lang_type(LANGUAGE_TYPE lang);
extern LANGUAGE_TYPE app_get_lang_type(void);
extern const char *app_get_lang_string(unsigned int offset, char *defaultStr);

#define APP_SET_LANG_TYPE(lang)         app_set_lang_type(lang)
#define APP_GET_LANG_TYPE()             app_get_lang_type()

#define LANG_GET_ID_BY_KEY(type, key)   ((unsigned int)(&(((type *)0)->key)))
#define LANG_GET_STR(id, default)       app_get_lang_string(id, default)

#define APP_GET_STR_BY_ID(id)           LANG_GET_STR(id, "not find key")
#define APP_GET_STR_ID(key)             LANG_GET_ID_BY_KEY(LANGUAGE_TRANSLATION_t, key)
#define APP_GET_STR(key, default)       LANG_GET_STR(APP_GET_STR_ID(key), default)


#ifdef __cplusplus
}
#endif

#endif


