/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_en_us_translation = {
    .key_nextstep         = "Next step",
    .key_cancel           = "Cancel",
    .key_alarm            = "Alarm",
    .key_remind_later     = "Remind me later",
    .key_delete           = "Delete",
    .key_everyday         = "Every day",
    .key_setting          = "Setting",
    .key_heart_rate       = "Heart rate",
    .key_about            = "About",
    .key_flashlight       = "Flash light",
    .key_music            = "Music",
    .key_powerOff         = "Power-off",
};

const language_info_t lang_en_us = {
    .locale = "English",
    .translation = &lang_en_us_translation,
};


