/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta
 * Generated at 2023-02-19 13:46:46
 * Version: 0x5538bf2a
 */

#include "Font_Lib.h"


const font_type_info_t Full_HarmonyOS_Sans_SC_KR_Regular_24_2Bpp_font_info =
{
    .font_name       = "Full_HarmonyOS_Sans_SC_KR_Regular_24_2Bpp",
    .bpp             = 2,
    .cmap_continued  = 1,
    .y_size          = 34,
    .y_dist          = 34,
    .baseline        = 28,
    .l_hight         = 19,
    .c_hight         = 19,
    .first_code      = 0x0,
    .last_code       = 0xffff,
    .cmap_offset     = 0x1000,
    .code_num        = 65535,
#if !CMAP_HASH_ENABLE
    .p_cmap_table    = NULL,
#else
    .p_cmap_table    = NULL,
#endif
};

