/*
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: 
*/
#ifndef _EXT_FONT_APP_H_
#define _EXT_FONT_APP_H_

#include "Font_Lib.h"

typedef enum FONTTYPE
{
    e_HarmonyOS_Sans_SC_Medium_24_2Bpp,
    e_fHarmonyOS_Sans_SC_Medium_24_2Bpp,
    e_fake_font,
    e_interior_font_HarmonyOS_Sans_SC_Medium_24_2bpp,
    e_FontTypeMax,
}FONTTYPE_ENUM;


extern bool app_ext_font_init(void);
extern FONTTYPE_ENUM app_font_get_type(const public_font_t *pFont);
extern public_font_t* app_type_get_font(FONTTYPE_ENUM font_type);

#endif//_EXT_FONT_APP_H_


