/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_fr_FR_translation = {
    .key_nextstep         = "Étape suivante",
    .key_cancel           = "Annuler",
    .key_alarm            = "Alarme",
    .key_remind_later     = "Rappeler plus tard",
    .key_delete           = "Supprimer",
    .key_everyday         = "Chaque jour",
    .key_setting          = "Configuration",
    .key_heart_rate       = "Fréquence cardiaque",
    .key_about            = "À propos",
    .key_flashlight       = "Lampe de poche",
    .key_music            = "Musique",
    .key_powerOff         = "Eteint",
};

const language_info_t lang_fr_FR = {
    .locale = "Français",
    .translation = &lang_fr_FR_translation,
};


