/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_es_ES_translation = {
    .key_nextstep         = "Siguiente paso",
    .key_cancel           = "Cancelar",
    .key_alarm            = "Alarma",
    .key_remind_later     = "Recordar más tarde",
    .key_delete           = "Eliminar",
    .key_everyday         = "Cada día",
    .key_setting          = "Configuración",
    .key_heart_rate       = "Ritmo cardíaco",
    .key_about            = "Acerca de",
    .key_flashlight       = "Linterna",
    .key_music            = "Música",
    .key_powerOff         = "Apagado",
};

const language_info_t lang_es_ES = {
    .locale = "Español",
    .translation = &lang_es_ES_translation,
};


