/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_ja_jp_translation = {
    .key_nextstep         = "次のステップ",
    .key_cancel           = "取り消す",
    .key_alarm            = "アラーム",
    .key_remind_later     = "スヌーズ",
    .key_delete           = "削除",
    .key_everyday         = "毎日",
    .key_setting          = "設定",
    .key_heart_rate       = "心拍数",
    .key_about            = "デバイス情報",
    .key_flashlight       = "フラッシュライト",
    .key_music            = "ミュージック",
    .key_powerOff         = "電源オフ",
};

const language_info_t lang_ja_jp = {
    .locale = "日本語",
    .translation = &lang_ja_jp_translation,
};


