/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_ru_RU_translation = {
    .key_nextstep         = "Следующий шаг",
    .key_cancel           = "Отмена",
    .key_alarm            = "Будильник",
    .key_remind_later     = "Напомнить позже",
    .key_delete           = "Удалить",
    .key_everyday         = "Ежедневно",
    .key_setting          = "Настройки",
    .key_heart_rate       = "Сердечный пульс",
    .key_about            = "О названии",
    .key_flashlight       = "Фонарик",
    .key_music            = "Музыка",
    .key_powerOff         = "Выключение",
};

const language_info_t lang_ru_RU = {
    .locale = "русский",
    .translation = &lang_ru_RU_translation,
};


