/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_zh_cn_translation = {
    .key_nextstep         = "下一步",
    .key_cancel           = "取消",
    .key_alarm            = "闹钟",
    .key_remind_later     = "稍后提醒",
    .key_delete           = "删除",
    .key_everyday         = "每天",
    .key_setting          = "设置",
    .key_heart_rate       = "心率",
    .key_about            = "关于",
    .key_flashlight       = "手电筒",
    .key_music            = "音乐",
    .key_powerOff         = "关机",
};

const language_info_t lang_zh_cn = {
    .locale = "简体中文",
    .translation = &lang_zh_cn_translation,
};


