/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_de_DE_translation = {
    .key_nextstep         = "Nächster Schritt",
    .key_cancel           = "Abbrechen",
    .key_alarm            = "Wecker",
    .key_remind_later     = "Später erinnern",
    .key_delete           = "Löschen",
    .key_everyday         = "Täglich",
    .key_setting          = "Einstellung",
    .key_heart_rate       = "Herzfrequenz",
    .key_about            = "Über",
    .key_flashlight       = "Taschenlampe",
    .key_music            = "Musik",
    .key_powerOff         = "Ausschalten",
};

const language_info_t lang_de_DE = {
    .locale = "Deutsch",
    .translation = &lang_de_DE_translation,
};


