/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

extern const language_info_t lang_en_us;
extern const language_info_t lang_zh_cn;
extern const language_info_t lang_zh_hk;
extern const language_info_t lang_de_DE;
extern const language_info_t lang_it_IT;
extern const language_info_t lang_ja_jp;
extern const language_info_t lang_pt_PT;
extern const language_info_t lang_es_ES;
extern const language_info_t lang_ru_RU;
extern const language_info_t lang_fr_FR;

static const language_info_t *language_pack[LANGUAGE_TYPE_MAX] = {
    &lang_en_us,
    &lang_zh_cn,
    &lang_zh_hk,
    &lang_de_DE,
    &lang_it_IT,
    &lang_ja_jp,
    &lang_pt_PT,
    &lang_es_ES,
    &lang_ru_RU,
    &lang_fr_FR,
};

//User Modification of Language
static LANGUAGE_TYPE lang_type = LANGUAGE_ZH_CN; // LANGUAGE_EN_US;

void app_set_lang_type(LANGUAGE_TYPE lang)
{
    lang_type = lang;
}

LANGUAGE_TYPE app_get_lang_type(void)
{
    return lang_type;
}

const char *app_get_lang_string(unsigned int offset, char *default_str)
{
    if (offset >= sizeof(LANGUAGE_TRANSLATION_t))
    {
        return "no keyname";
    }
    const char *lang_str = ((LANG_TRANSLA_ITEM_t *)((unsigned int)language_pack[lang_type]->translation + offset))->lang_string;
    return (*lang_str) ? lang_str : default_str;
}


