/**
 * This file is generated by py_FontMaker generation tools
 * Please DO NOT modify this file
 *
 * author: John
 * github: https://github.com/ZJ-TEK/Py_FontMaker_Beta.git
 */
#include "language.h"

static const LANGUAGE_TRANSLATION_t lang_pt_PT_translation = {
    .key_nextstep         = "Próximo passo",
    .key_cancel           = "Cancelar",
    .key_alarm            = "Alarme",
    .key_remind_later     = "Tocar mais tarde",
    .key_delete           = "Deletar",
    .key_everyday         = "Todos os dias",
    .key_setting          = "Configuração",
    .key_heart_rate       = "Frequência",
    .key_about            = "Sobre",
    .key_flashlight       = "Lanterna",
    .key_music            = "Música",
    .key_powerOff         = "Desligar",
};

const language_info_t lang_pt_PT = {
    .locale = "Português",
    .translation = &lang_pt_PT_translation,
};


